spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sapphire
    username: admin
    password: welcome
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/sapphire-realm
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: sapphire-group
      auto-offset-reset: earliest
    listener:
      ack-mode: record